package com.projet.dwa.inscription;

import java.io.Serializable;
import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Inscription implements Serializable {

    // Generated by VSCode
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "hibernate_sequence")
    private Long id;

    @Column(name = "code_postal")
    private String codePostal;

    private String commune;

    @Column(name = "numero_et_voie")
    private String numeroEtVoie;

    private String pays;

    private String civilite;

    @Column(name = "date_de_naissance")
    private Date dateDeNaissance;

    private String nom;

    private String prenom;

    @Column(name = "reference_dossier")
    private String referenceDossier;

    @Column(name = "diplome_id")
    private Long diplomeId;

    public Inscription() {

    }

    public String getCodePostal() {
        return codePostal;
    }

    public String getCommune() {
        return commune;
    }

    public String getNumeroEtVoie() {
        return numeroEtVoie;
    }

    public String getPays() {
        return pays;
    }

    public String getCivilite() {
        return civilite;
    }

    public Date getDateDeNaissance() {
        return dateDeNaissance;
    }

    public String getNom() {
        return nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public String getReferenceDossier() {
        return referenceDossier;
    }

    public Long getDiplomeId() {
        return diplomeId;
    }

    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }

    public void setCommune(String commune) {
        this.commune = commune;
    }

    public void setNumeroEtVoie(String numeroEtVoie) {
        this.numeroEtVoie = numeroEtVoie;
    }

    public void setPays(String pays) {
        this.pays = pays;
    }

    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    public void setDateDeNaissance(Date dateDeNaissance) {
        this.dateDeNaissance = dateDeNaissance;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public void setReferenceDossier(String referenceDossier) {
        this.referenceDossier = referenceDossier;
    }

    public void setDiplomeId(Long diplomeId) {
        this.diplomeId = diplomeId;
    }

}